language: go

sudo: required

go:
  - 1.9.x
  - master

env:
  - INTEGRATION=true GOOS=linux
  - INTEGRATION=false GOOS=linux

services:
  - docker

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3 python3-pip
  - make install-deps
  - make pull-linters

install:
  - ./test/scripts/install_minikube.sh
  - kubectl create -f test/data/crd.yml
  - kubectl get crd
  - dep ensure
  - sudo pip3 install -r ./requirements.txt

script:
  - make lint
  - make test
  - make build
  - make docker-build-test
  - make LOSTROMOS_IP_AND_PORT=`minikube service lostromos --url | cut -c 8-` integration-tests
  - kubectl logs lostromos
  - make coverage

after_script:
  - ./lostromos version

after_success:
  - bash <(curl -s https://codecov.io/bash)
