language: go

services:
  - docker

go:
  - 1.9.x
  - master

env:
  - INTEGRATION=true
  - INTEGRATION=false

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_install:
  - make install-deps
  - make pull-linters

install:
  - dep ensure

script:
  - make lint
  - if [ $INTEGRATION == 'true' ]; then
      make build || travis_terminate 1;
      ./test-scripts/cluster-up-minikube.sh  || travis_terminate 1;
      make integration-tests || travis_terminate 1;
    else
      make test || travis_terminate 1;
      make build || travis_terminate 1;
      make coverage || travis_terminate 1;
    fi

after_script:
  - ./lostromos version

after_success:
  - bash <(curl -s https://codecov.io/bash)
