language: go

services:
  - docker

go:
  - 1.9.x
  - master

matrix:
  allow_failures:
  - master

before_install:
  - make install-deps
  - make pull-linters

install:
  - dep ensure

script:
  - make

after_script:
  - ./lostromos version
