language: go

services:
  - docker

go:
  - 1.9.x
  - master

matrix:
  fast_finish: true
  allow_failures:
  - go: master

before_install:
  - make install-deps
  - make pull-linters
  - sudo apt-get update
  - sudo apt-get -y install python3-pip python3

install:
  - dep ensure
  - sudo pip3 install -r ./requirements.txt
  - ./test-scripts/install_minikube.sh

script:
  - make lint
  - make test
  - make build
  - make integration-tests
  - make coverage

after_script:
  - ./lostromos version

after_success:
  - bash <(curl -s https://codecov.io/bash)
