language: go

services:
  - docker

go:
  - 1.9.x
  - master

matrix:
  allow_failures:
  - master

before_install:
  - make install-deps
  - make pull-linters

install:
  - dep ensure

script:
  - make travis

after_script:
  - ./lostromos version

after_success:
  - bash <(curl -s https://codecov.io/bash)
