[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "^4.0.0"

# Found in https://github.com/kubernetes/client-go/blob/release-4.0/Godeps/Godeps.json
[[override]]
  name = "k8s.io/apimachinery"
  revision = "917740426ad66ff818da4809990480bcc0786a77"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/golang/mock"
  version = "v1.0.0"
