---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: characters.stable.nicolerenee.io
spec:
  scope: Namespaced
  group: stable.nicolerenee.io
  version: v1
  names:
    kind: Character
    plural: characters
    singular: character
